spring:
  r2dbc:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: r2dbc:postgresql://${POSTGRES_URI}:${POSTGRES_PORT:5432}/business

  data:
    r2dbc:
      repositories:
        enabled: true

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yaml
    url: jdbc:postgresql://${POSTGRES_URI}:${POSTGRES_PORT:5432}/business
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
